# Generated by Django 5.1.6 on 2025-04-10 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('p_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('price', models.IntegerField()),
                ('p_rating_count', models.IntegerField(default=0)),
                ('rating_count_user', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('help', models.TextField(max_length=1000)),
                ('p_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('reply', models.TextField(blank=True, default='no-reply-yet', max_length=2000, null=True)),
                ('urgency_score', models.IntegerField(blank=True, default=0, null=True)),
                ('help_type', models.IntegerField(blank=True, choices=[(5, 'techinical problem'), (4, 'warrenty related'), (3, 'return releted'), (2, 'offer releted'), (1, 'product inquiery'), (0, 'other')], default=0, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.product')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(max_length=1000)),
                ('rating', models.IntegerField(choices=[(5, 'excellent'), (4, 'best'), (3, 'good'), (2, 'satisfactory'), (1, 'not-satisfactory'), (0, 'not-sure')], default=0)),
                ('reply', models.TextField(blank=True, default='no-reply-yet', max_length=2000, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.product')),
            ],
        ),
    ]
